model_name: Qwen/Qwen3-8B
hook_point: blocks.{layer}.hook_resid_pre
hook_point_layer: [0, 1, 2, 3, 4]
dataset_path: ashaba1in/small_openwebtext
is_dataset_tokenized: false
context_size: 128
d_in: 4096

# SAE
expansion_factor: 4
b_dec_init_method: mean

# Training
lr: 3e-4
l1_coefficient: 1e-6
lr_scheduler_name: constantwithwarmup
lr_warm_up_steps: 1000
train_batch_size: 2096
n_batches_in_buffer: 32
total_training_tokens: 8000000
store_batch_size: 16

eval_every_n_steps: 200
logger_backend: clearml

n_checkpoints: 0 # change to save checkpoints
checkpoint_path: checkpoints

push_to_hub: false # change to push to hub
hub_repo_id: ExplosionNuclear/Qwen
hub_private: false

# Other
device: auto  # auto|cuda|cpu
seed: 42
dtype: float32


